{% set name = "Binette" %}
{% set version = "0.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  url: https://github.com/genotoul-bioinfo/{{ name|lower }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed -vv .

requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - python >=3.7
    - numpy =1.19.2
    - diamond =2.0.4
    - pandas =1.4.0
    - checkm2
    - requests
    - packaging
    - tqdm
    - networkx >=3
    - pyfastx
    - pyrodigal >=2

test:
  imports:
    - binette
  commands:
    - binette -h

about:
  home: https://github.com/genotoul-bioinfo/{{ name|lower }}
  doc_url: https://binette.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "A fast and accurate binning refinement tool to constructs high quality MAGs from the output of multiple binning tools."
